language: "python"
python:
   - "2.7"
   - "pypy"
install:
  - pip install flake8
  - pip install -r requirements.txt
#before_script:
script:
   - flake8 --max-line-length=100 --ignore=F401 --exclude=tests/ .
#script:
#   coverage run --source=geojson setup.py test
#after_success:
#   coveralls